version: '3'
services:
    class.api:
        image: classapi
        depends_on:
            - redis
            - mongo
        build:
            context: .
            dockerfile: ClassApi/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - 5002:8080
            - 5003:8081