version: '3'
services:
    class.api:
        image: classapi
        depends_on:
            - redis
            - mongo
        build:
            context: .
            dockerfile: ClassApi/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        ports:
            - 5002:8080
            - 5003:8081
    user.api:
        image: userapi
        build:
            context: .
            dockerfile: UserApi/Dockerfile
        ports:
            - 5000:8080
            - 5001:8081
    redis:
        image: redis
        ports:
            - 6379:6379
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongo-volume:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
    mongo-express:
        image: mongo-express
        ports:
            - 5004:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongo
volumes:
    mongo-volume:
        driver: local